version: "3.9"

services:
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always

  migration:
    image: flyway/flyway:10.8
    command: -url=jdbc:postgresql://db:5432/${DB_DATABASE} -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=120 migrate
    volumes:
      - ./db/migration:/flyway/sql
    depends_on:
      - db

  app:
    image: node:21
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    ports:
      - "4321:4321"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    restart: always

volumes:
  postgres-data-volume:
